
    drop table if exists acct_group;

    drop table if exists acct_group_permission;

    drop table if exists acct_user;

    drop table if exists acct_user_group;
    
    drop table if exists event_E0001;

    create table acct_group (
        id bigint generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    ) ;

    create table acct_group_permission (
        group_id bigint not null,
        permission varchar(255) not null,
        foreign key(group_id) references acct_group(id),
    ) ;

    create table acct_user (
        id bigint generated by default as identity,
        email varchar(255),
        login_name varchar(255) not null unique,
        name varchar(255),
        password varchar(255),
        primary key (id)
    ) ;

    create table acct_user_group (
        user_id bigint not null,
        group_id bigint not null,
     	primary key(user_id,group_id),
        foreign key(user_id) references acct_user(id),
        foreign key(group_id) references acct_group(id)
    ) ;

     create table event_E0001 (
        id bigint generated by default as identity,
        rel_group  varchar(255),
        rel_code varchar(255) not null unique,
        ITEMS_FOR_RELEASE  varchar(255),
        PO_NUMBER varchar(255), 
        VENDOR varchar(255),
        primary key (id)
    ) ;
    
    create table task_message(
        id bigint generated by default as identity,
        event_type  varchar(255),
        user_id  bigint,
        trigger_time varchar(255),
        task_priority bigint,
        task_status varchar(255),
        input_paras varchar(255),
        primary key (id)
        
    );
    
     create table task_log(
        id bigint generated by default as identity,
        task_id bigint not null,
        log_type  varchar(255),
        log_time  date,
        log_desc varchar(255),
        foreign key(task_id) references task_message(id),
        primary key (id)
        
    );
    
    create table DM_COMPANY(
    COMPANY_GUID varchar(255),
    CMY_NAME varchar(255),
    CMY_DES  varchar(255),
    CMY_STATUS varchar(255),
    EXPIRATION_DATE  date,
    CREATED_BY varchar(255),
    CHANGED_ON date,
    CHANGED_BY varchar(255),
    COMMENTS varchar(255),
    primary key (COMPANY_GUID)
    
    );
    
    create table DM_EVENT(
     EVENT_ID varchar(255),
     EVENT_NAME varchar(255),
     EVENT_DES varchar(255),
     COMMENTS varchar(255),
     primary key (EVENT_ID)
    );
    
   create table  DM_COMPANY_EVENT(
    COMPANY_GUID varchar(255) not null,
    EVENT_ID varchar(255) not null,
    EVENT_STATUS varchar(255),
    COMMENTS varchar(255),
    primary key(COMPANY_GUID,EVENT_ID),
    foreign key(COMPANY_GUID) references DM_COMPANY(COMPANY_GUID),
    foreign key(EVENT_ID) references DM_EVENT(EVENT_ID)
    );
    
 
